version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "valuation-app"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-1xh96xbpizncp"
s3_prefix = "valuation-app"
region = "us-east-2"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"

